name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutRepo
        uses: actions/checkout@v2
      - name: run test
        run: |
          echo "HELLO WORLD"